import {SoftWorld,makeMaterial,MATERIALS,buildBeam,buildRope,buildCloth,buildBlockCluster} from './softsolver.js';
const w=new SoftWorld({seed:3,substeps:4,iterations:1});
w.heightfield=(x,z)=>0.15*Math.sin(x*0.7)*Math.cos(z*0.5); w.heightfieldMax=0.15;
const wood=makeMaterial(MATERIALS.wood),rope=makeMaterial(MATERIALS.rope),cloth=makeMaterial(MATERIALS.cloth),stone=makeMaterial(MATERIALS.stone),mortar=makeMaterial(MATERIALS.mortar);
for(let k=0;k<10;k++) buildBeam(w,{a:[-6,1+0.3*k,-6+k*1.2],b:[-5.2,1+0.3*k,-6+k*1.2],width:0.1,height:0.1,mat:wood,pin:'start'});
for(let k=0;k<10;k++) buildRope(w,{a:[-4,4,-6+k*1.2],b:[-1,4,-6+k*1.2],slack:1.1,segments:24,mat:rope,pin:'both'});
buildCloth(w,{origin:[0,6,-6],du:[6,0,0],dv:[0,-4,0],nu:32,nv:28,mat:cloth,pin:['top']});
w.wind=[2,0,1.5];
buildBlockCluster(w,{mat:stone,mortar,size:[0.5,0.25,0.25],counts:[6,12,3],origin:[3,0.2,-3]});
console.log(w.n,w.nd,w.nw);
w.step(1/60); w.step(1/60);
const T={};
const wrap=(name)=>{const f=w[name].bind(w); w[name]=(...a)=>{const t=performance.now(); const r=f(...a); T[name]=(T[name]||0)+performance.now()-t; return r;}};
['_predict','_vbd','_collide','_pairs','_finish','_aero'].forEach(wrap);
const N=200; const t0=performance.now(); for(let i=0;i<N;i++) w.step(1/60); const tot=(performance.now()-t0)/N;
console.log('total',tot.toFixed(2),Object.entries(T).map(([k,v])=>k+' '+(v/N).toFixed(2)).join('  '));
