// Realistic baked fire (FW branch) check. usage: node qa/fire-check.mjs [desktop|phone] [out.json]
// Starts its own static server on a free port (never 8773) and ONE headless Chrome (killed by PID at the end). The renderer is SwiftShader (software):
// frame times from it are comparisons between scenes, not device figures. While a section drives the effects by hand, the game loop is paused (window.__qaHold).
import fs from 'fs'; import path from 'path';
import { boot, log, sleep, ROOT } from './fire-lib.mjs';
const profile = process.argv[2] === 'phone' ? 'portrait' : 'desktop', outFile = process.argv[3] || path.join(ROOT, 'qa', profile === 'desktop' ? 'fire-check-report.json' : 'fire-check-phone-report.json');
const results = [], rep = { profile, perf: {}, notes: [] };
const ok = (name, cond, extra) => { results.push({ name, pass: !!cond, extra }); log(cond ? 'PASS' : 'FAIL', name, extra === undefined ? '' : JSON.stringify(extra)); };
const g = await boot(profile); const b = g.b, srv = g.srv;
const J = async (expr) => { const r = await b.ev(`(async()=>{ try { ${expr} } catch (e) { return JSON.stringify({ __err: String(e && e.stack || e).slice(0, 500) }); } })()`); return typeof r === 'string' && /^[\[{]/.test(r) ? JSON.parse(r) : r; };
const wait = async (cond, ms = 90000, step = 400) => { const t0 = Date.now(); while (Date.now() - t0 < ms) { if (await b.ev(cond, true)) return true; await sleep(step); } return false; };
const tick = (n, dt = 0.05) => `for (let i = 0; i < ${n}; i++) F.tick(${dt});`;
const PRE = `const sc = __sc, F = sc.FW, R = F.R; window.__qaHold = true;`;
const settle = async (types) => { await J(`${PRE} for (let i = 0; i < 400; i++) { F.tick(0.02); const ts = ${JSON.stringify(types)}.map(n => F.types[n]); if (ts.every(t => t && (t.state === 'ready' || t.state === 'bad'))) break; await new Promise(r => setTimeout(r, 250)); } return 1`); };
try {
  const PH = profile !== 'desktop';
  // ---------------------------------------------------------------- loading
  const st0 = await J(`${PRE} F.tick(0.05); for (let i = 0; i < 60 && !F.ready; i++) { await new Promise(r => setTimeout(r, 300)); F.tick(0.05); } return JSON.stringify({ ready: F.ready, q: F.q, types: Object.keys(F.types), cap: F.cap() })`);
  ok('atlas json loaded, quality is ' + (PH ? 'low' : 'high') + ' by default', st0.ready && st0.q === (PH ? 'low' : 'high'), st0);
  const before = srv.stats.hits.filter(h => /fire_(torch|campfire|barrel)_/.test(h)).length;
  ok('lazy: no torch, campfire or barrel atlas fetched before the first such fire', before === 0, { before });
  const spG = JSON.parse(await b.ev("JSON.stringify(__fxFind('grass'))")); const sp = spG || JSON.parse(await b.ev("JSON.stringify(__fxFind('sand'))")); if (!spG) rep.notes.push('no open grass found: the spread test is skipped');
  const setCam = (x, y, z, tx, ty, tz) => b.ev(`(()=>{ const c = __sc.camera; c.position.set(${x}, ${y}, ${z}); c.lookAt(${tx}, ${ty}, ${tz}); c.updateMatrixWorld(true); const L = __sc.Snd.L; L.x = ${x}; L.y = ${y}; L.z = ${z}; return 1 })()`);
  await b.ev(`__fxGo(${sp[0]},${sp[1]},0,0.1,2);1`); await setCam(sp[0], (await b.ev(`Math.max(__sc.heightAt(${sp[0]},${sp[1]}),0)`)) + 2, sp[1], sp[0], 1.5, sp[1] + 10);
  await J(`${PRE} sc.wind.v.x = 0; sc.wind.v.z = 3; const gy = Math.max(sc.heightAt(${sp[0]}, ${sp[1] + 6}), 0); window.__cf = F.spawn('campfire', ${sp[0]}, gy + 0.05, ${sp[1] + 6}, { sc: 1, F: 1, dur: 9 }); F.tick(0.05); return 1`);
  await settle(['campfire']);
  const hits = srv.stats.hits.filter(h => /fire_campfire_/.test(h)), tor = srv.stats.hits.filter(h => /fire_torch_/.test(h)).length;
  ok('lazy: the campfire type loads on first use, torch still untouched', hits.length >= 3 && tor === 0, { hits: hits.map(h => h.split('/').pop()), tor });
  ok(PH ? 'phone loads the low atlases' : 'desktop loads the full atlases', hits.some(h => PH ? /_low\.webp/.test(h) : /campfire_flame\.webp/.test(h)) && (PH ? !hits.some(h => /campfire_flame\.webp$/.test(h)) : true), hits.map(h => h.split('/').pop()));
  // ---------------------------------------------------------------- lifecycle
  const lc = await J(`${PRE} const f = window.__cf; f.st = 0; f.state = 'ignite'; f.age = 0; f.dur = 9; const seq = []; let last = '', t = 0, tIgn = 0, tGrow = 0, tBurnStart = 0, tDecay = 0, tOut = 0; for (let i = 0; i < 400; i++) { F.tick(0.05); t += 0.05; if (f.dead) { tOut = t; break; } if (f.state !== last) { seq.push(f.state); last = f.state; if (f.state === 'grow') tIgn = t; if (f.state === 'burn') tGrow = t; if (f.state === 'decay') tDecay = t; } } return JSON.stringify({ seq, tIgn, tGrow, tDecay, tOut })`);
  ok('lifecycle: ignite, grow, burn, decay, out in order', JSON.stringify(lc.seq) === JSON.stringify(['ignite', 'grow', 'burn', 'decay']) && lc.tOut > 0, lc);
  ok('lifecycle durations: ignite 1.25 s, growth 2.5 s, decay 2.5 s once the fuel (9 s of burning) runs low', Math.abs(lc.tIgn - 1.25) < 0.2 && Math.abs(lc.tGrow - lc.tIgn - 2.5) < 0.2 && Math.abs(lc.tDecay - (lc.tGrow + 9 - 2.5)) < 0.4 && Math.abs(lc.tOut - lc.tDecay - 2.5) < 0.5, lc);
  const ex = await J(`${PRE} const gy = Math.max(sc.heightAt(${sp[0]}, ${sp[1] + 6}), 0); const f = F.spawn('campfire', ${sp[0]}, gy + 0.05, ${sp[1] + 6}, { sc: 1, state: 'burn', dur: 99 }); F.tick(0.05); F.water(f.x, f.z, 2, 5); const s1 = f.state; const cn = (F.types.campfire.clips.extinguish || {}).name; for (let i = 0; i < 12; i++) F.tick(0.05); const clipNow = f.cn; for (let i = 0; i < 60; i++) F.tick(0.05); return JSON.stringify({ s1, cn, clipNow, dead: f.dead, ext: F.stats.extinguished })`);
  ok('water extinguishes: the extinguish clip plays and the fire ends', ex.s1 === 'extinguish' && ex.clipNow === 'extinguish' && ex.dead, ex);
  // ---------------------------------------------------------------- caps
  await J(`${PRE} for (const f of F.fires.slice()) F.kill(f, true); return 1`);
  await J(`${PRE} for (const n of ['campfire', 'barrel', 'vehicle', 'tree_crown', 'grass']) F.need(n); return 1`); await settle(['campfire', 'barrel', 'vehicle', 'tree_crown', 'grass']);
  const cap = await J(`${PRE} const cp = sc.camera.position, names = ['campfire', 'barrel', 'vehicle', 'tree_crown', 'grass']; for (let i = 0; i < 100; i++) { const a = i * 0.7, d = 8 + (i % 20) * 3, x = cp.x + Math.sin(a) * d, z = cp.z + Math.cos(a) * d; F.spawn(names[i % 5], x, Math.max(sc.heightAt(x, z), 0) + 0.05, z, { sc: 1, F: 1, state: 'burn', dur: 999, pri: 1 }); } for (let i = 0; i < 6; i++) F.tick(0.05); const c = F.cap(); return JSON.stringify({ fires: F.fires.length, anim: F.stats.anim, inst: F.R.inst, calls: F.R.calls, capFires: c.fires, capInst: c.inst, dropped: F.R.dropped })`);
  ok('caps hold with 100 ignitions (fires at most 2 x cap + 20, animated at most cap, draw calls few)', cap.fires <= cap.capFires * 2 + 20 && cap.anim <= cap.capFires && cap.calls <= (PH ? 40 : 60), cap);
  rep.caps = cap;
  // ---------------------------------------------------------------- haze, sensors, uniforms
  const hz = await J(`${PRE} sc.DIST.setPref(true); sc.DIST.tick(0.05); const live = sc.DIST.live; F.tick(0.05); const hs = F.hazeSources; const types = new Set(F.alive.filter(f => f.vis).map(f => f.name)); return JSON.stringify({ live, hs, types: [...types] })`);
  ok('heat haze: one DIST source per visible fire type descriptor (when the distortion engine is live)', hz.live ? hz.hs > 0 : true, hz);
  if (!hz.live) rep.notes.push('DIST.live false in this headless renderer: haze feed not exercised');
  const sens = await J(`${PRE} F.tick(0.02); const out = {}; const mesh = (k) => Object.values(R.combos).filter(c => c.def.key.includes(k)); sc.SENSOR.value = 1; sc.renderer.render(sc.scene, sc.camera); out.thermal = { heat: mesh(':heat:').reduce((a, c) => a + c.geo.instanceCount, 0), flame: mesh(':flame:').reduce((a, c) => a + c.geo.instanceCount, 0), smoke: mesh(':smoke:').reduce((a, c) => a + c.geo.instanceCount, 0) }; sc.SENSOR.value = 2; sc.renderer.render(sc.scene, sc.camera); const fl = mesh(':flame:')[0]; out.nv = { uniform: fl.mat.uniforms.uSensor.value, flame: mesh(':flame:').reduce((a, c) => a + c.geo.instanceCount, 0) }; sc.SENSOR.value = 0; sc.renderer.render(sc.scene, sc.camera); out.colour = { heat: mesh(':heat:').reduce((a, c) => a + c.geo.instanceCount, 0), flame: mesh(':flame:').reduce((a, c) => a + c.geo.instanceCount, 0) }; return JSON.stringify(out)`);
  ok('thermal view draws the heat atlases only (flame and smoke hidden)', sens.thermal.heat > 0 && sens.thermal.flame === 0 && sens.thermal.smoke === 0, sens.thermal);
  ok('night vision sets the sensor uniform and keeps the flames (they bloom in the shader)', sens.nv.uniform === 2 && sens.nv.flame > 0, sens.nv);
  ok('colour view draws flames and hides the heat layer', sens.colour.flame > 0 && sens.colour.heat === 0, sens.colour);
  // ---------------------------------------------------------------- spread, debris ignition (clean slate)
  await J(`${PRE} for (const f of F.fires.slice()) F.kill(f, true); F.G.fronts.length = 0; F.G.spots.length = 0; return 1`);
  await J(`${PRE} for (const n of ['spot_fire', 'front_lead', 'front_body', 'front_trail', 'lick']) F.need(n); return 1`); await settle(['spot_fire', 'front_lead', 'front_body', 'front_trail']);
  const wv = [0, 4];
  const sprd = !spG ? { front: true, advance: 99, along: 99, skipped: true } : await J(`${PRE} sc.wind.v.x = ${wv[0]}; sc.wind.v.z = ${wv[1]}; F.tick(0.05); const s = F.igniteGround(${sp[0]}, ${sp[1] + 1}, { convert: true }); for (let i = 0; i < 160 && !F.G.fronts.length; i++) F.tick(0.1); const fr = F.G.fronts[0]; if (!fr) return JSON.stringify({ front: false, spot: !!s, spots: F.G.spots.length }); const d0 = fr.d, x0 = fr.x0 + fr.ux * fr.d, z0 = fr.z0 + fr.uz * fr.d; for (let i = 0; i < 60; i++) F.tick(0.1); const x1 = fr.x0 + fr.ux * fr.d, z1 = fr.z0 + fr.uz * fr.d, wl = Math.hypot(F.wind.x, F.wind.z); return JSON.stringify({ front: true, advance: fr.d - d0, along: ((x1 - x0) * F.wind.x + (z1 - z0) * F.wind.z) / wl, speed: fr.speed, hw: fr.hw, cols: fr.cols.length, alive: fr.cols.filter(c => !c.dead).length })`);
  ok('a spot fire grows into a front and the front advances downwind', sprd.front && sprd.advance > 1 && sprd.along > 1, sprd);
  rep.spread = sprd;
  const deb = await J(`${PRE} for (const f of F.fires.slice()) F.kill(f, true); F.G.fronts.length = 0; F.G.spots.length = 0; const t = sc.trees.find(t => !t.dead && Math.hypot(t.x - sc.camera.position.x, t.z - sc.camera.position.z) < 80); if (!t) return JSON.stringify({ tree: false }); const n0 = sc.burning.length; F.debrisLand({ x: t.x + 0.5, y: t.h, z: t.z, s: 0.15, age: 1 }); return JSON.stringify({ tree: true, before: n0, after: sc.burning.length, spots: F.G.spots.length, patches: sc.HEATP.length })`);
  ok('a burning chunk that lands ignites a tree beside it', deb.tree && deb.after > deb.before, deb);
  // ---------------------------------------------------------------- explosions and debris
  await J(`${PRE} for (const n of ['blast_medium', 'blast_fuel', 'blast_ground', 'blast_small', 'debris_med', 'debris_fast', 'debris_slow', 'splash_fire', 'spatter_fan', 'oil_slick', 'pool', 'smoke_column']) F.need(n); F.needParticles(); return 1`);
  await settle(['blast_medium', 'blast_fuel', 'blast_small', 'debris_med', 'debris_slow', 'debris_fast', 'splash_fire', 'oil_slick', 'pool', 'smoke_column']);
  const bl = await J(`${PRE} const x = ${sp[0]} + 8, z = ${sp[1]} + 14, gy = Math.max(sc.heightAt(x, z), 0); sc.DEB.p.length = 0; const n0 = F.blastStats.n; sc.blast(x, gy, z, { R: 11, dmg: 1, crater: 0, depth: 0, owner: null, quiet: true, name: 'Vehicle explosion' }); for (let i = 0; i < 4; i++) F.tick(0.05); const fl = sc.DEB.p.filter(d => d.fl).length; return JSON.stringify({ n: F.blastStats.n - n0, last: F.blastStats.last, flaming: fl, deb: sc.DEB.p.length, parts: F.P.list.length, black: F.fires.filter(f => f.mode === 'blast').map(f => f.name + ':' + f.state + ':' + f.black) })`);
  ok('blast() starts a baked fireball with embers, and flames on a share of the thrown chunks', bl.n === 1 && bl.black.length > 0 && bl.flaming > 0 && bl.parts > 0, bl);
  const sp2 = await J(`${PRE} const cp = sc.camera.position; const n0 = F.fires.filter(f => f.name === 'splash_fire' || f.name === 'pool' || f.name === 'oil_slick').length; F.fuelSplash(cp.x + 20, cp.z + 20, 6, 4); F.spill(cp.x + 20, cp.z + 20, { kind: 'fuel', r: 2, dur: 30 }); F.tick(0.05); const n1 = F.fires.filter(f => f.name === 'splash_fire' || f.name === 'pool' || f.name === 'oil_slick').length; return JSON.stringify({ n0, n1 })`);
  ok('thrown fuel splashes and spills become pool fires', sp2.n1 >= sp2.n0 + 3, sp2);
  // ---------------------------------------------------------------- vehicles, boats, objects
  const vh = await J(`${PRE} const v = sc.BVL.find(v => !v.dead && !v.heli); if (!v) return JSON.stringify({ v: false }); v.burn = 1; for (let i = 0; i < 4; i++) F.tick(0.05); const r1 = F.fires.filter(f => f.own && f.own.kind === 'veh').map(f => f.name); v.burn = 6; for (let i = 0; i < 4; i++) F.tick(0.05); const r2 = F.fires.filter(f => f.own && f.own.kind === 'veh').map(f => f.name); return JSON.stringify({ v: true, r1, r2 })`);
  ok('a burning vehicle gets an engine fire first and then the whole-vehicle fire', vh.v && vh.r1.includes('vehicle_engine') && (vh.r2.includes('vehicle') || vh.r2.includes('vehicle_small')), vh);
  const bt = await J(`${PRE} const bt = sc.boats.find(b => !b.sunk && b.sp && b.body); if (!bt) return JSON.stringify({ boat: false }); bt.fire = 0.6; bt.fireT = 30; for (let i = 0; i < 4; i++) F.tick(0.05); const n = F.fires.filter(f => f.name === 'boat_deck').length; bt.fire = 0; for (let i = 0; i < 4; i++) F.tick(0.05); const ext = F.fires.filter(f => f.name === 'boat_deck' && f.state === 'extinguish').length; return JSON.stringify({ boat: true, n, ext })`);
  ok('a boat on fire gets deck fires, and they go out when the fire is put out', bt.boat && bt.n > 0 && bt.ext > 0, bt);
  // ---------------------------------------------------------------- steam, mist, fog
  await J(`${PRE} F.A.need('steam_burst'); F.A.need('splash_medium'); F.A.need('mist_bow'); F.A.need('steam_engine'); return 1`);
  await J(`${PRE} for (let i = 0; i < 400; i++) { F.tick(0.02); const T = F.A.types; if (['steam_burst', 'splash_medium', 'mist_bow', 'steam_engine'].every(n => T[n] && T[n].state !== 'loading')) break; await new Promise(r => setTimeout(r, 250)); } return 1`);
  const stm = await J(`${PRE} for (const f of F.fires.slice()) F.kill(f, true); const cp = sc.camera.position, x = cp.x + 6, z = cp.z + 12; const f = F.spawn('barrel', x, Math.max(sc.heightAt(x, z), 0) + 0.05, z, { sc: 1, state: 'burn', dur: 99 }); F.tick(0.05); const nb = F.A.fx.filter(q => q.type === 'steam_burst').length; F.water(x, z, 2, 9); F.tick(0.05); const nb2 = F.A.fx.filter(q => q.type === 'steam_burst').length; const hs = F.A.fx.some(q => q.type === 'steam_burst'); const hz = F.A.types.steam_burst.P.haze; return JSON.stringify({ nb, nb2, hs, haze: hz && hz.strength, err: F.A.err })`);
  ok('putting a fire out with water makes a steam burst (with a haze descriptor)', stm.nb2 > stm.nb && stm.haze > 0, stm);
  const spl = await J(`${PRE} const cp = sc.camera.position; const r = F.splash(cp.x + 3, cp.z + 3, 0, 1.5); F.tick(0.05); return JSON.stringify({ r, fx: F.A.fx.filter(q => /^splash/.test(q.type)).length })`);
  ok('a water splash plays a baked splash clip instead of the procedural column', spl.r && spl.fx > 0, spl);
  const bd = await J(`${PRE} for (const f of F.fires.slice()) F.kill(f, true); F.G.bld.length = 0; const p = sc.props.find(p => p.item && /^b-(house|warehouse|office|workshop)/.test(p.item.id || '') && p.item.box); if (!p) return JSON.stringify({ building: false }); p._fwBurn = 0; for (const n of ['window', 'doorway', 'roof']) F.need(n); const ok = F.igniteBuilding(p); for (let i = 0; i < 200; i++) { F.tick(0.1); if (i % 10 === 0) await new Promise(r => setTimeout(r, 30)); } const names = F.fires.filter(f => ['window', 'doorway', 'roof'].includes(f.name)); return JSON.stringify({ building: true, ok, id: p.item.id, windows: names.filter(f => f.name === 'window').length, doorway: names.filter(f => f.name === 'doorway').length, roof: names.filter(f => f.name === 'roof').length, states: [...new Set(names.map(f => f.state))] })`);
  ok('a building catches fire: window fires, a doorway fire and a roof fire', bd.building && bd.ok && bd.windows >= 2 && bd.doorway >= 1 && bd.roof >= 1, bd);
  const am = await J(`${PRE} for (const f of F.fires.slice()) F.kill(f, true); const bt = sc.boats.find(b => !b.sunk && b.sp && b.body); const out = { boat: !!bt }; if (bt) { sc.camera.position.set(bt.body.position.x + 15, bt.body.position.y + 4, bt.body.position.z); sc.camera.updateMatrixWorld(true); bt.body.velocity.x = 6; bt.body.velocity.z = 0; F.A.bows(0.3); out.bow = !!(bt._fwbow && !bt._fwbow.dead); bt.body.velocity.x = 0; } const key = {}; F.hosePt(key, 0, 3, 0, 20, 2, 5); out.hose = F.A.fx.some(q => q.type === 'spray_cone'); F.geyser({ x: 5, z: 5 }); out.geyser = F.A.fx.some(q => q.type === 'steam_geyser'); sc.wind.v.x = 5; sc.wind.v.z = 1; F.tick(0.05); const c0 = sc.camera.position.clone(); sc.camera.position.set(60, 3, 118); sc.camera.updateMatrixWorld(true); F.A.surfFx.length = 0; for (let i = 0; i < 6; i++) F.A.surf(3); out.surf = F.A.surfFx.length; sc.camera.position.copy(c0); out.rainTick = typeof F.rainTick === 'function'; return JSON.stringify(out)`);
  ok('bow mist for a fast boat, a hose spray cone, a geyser column and surf mist on the shore are created', am.boat && am.bow && am.hose && am.geyser && (PH || am.surf > 0), am);
  const fg = await J(`${PRE} const w = sc.wx; const pump = async (n, dt) => { for (let i = 0; i < n; i++) { F.tick(dt); if (i % 8 === 0) await new Promise(r => setTimeout(r, 40)); } }; w.fog = 0; w.imp.fog = true; await pump(4, 0.5); const n0 = F.A.tiles.length; w.fog = 2; await pump(220, 0.5); const n2 = F.A.tiles.length, w2 = Object.assign({}, F.A.want); w.fog = 0; await pump(260, 0.5); const n3 = F.A.tiles.length; return JSON.stringify({ n0, n2, n3, bank: w2.fog_bank, sea: w2.fog_sea, types: [...new Set(F.A.tiles.map(t => t.type))] })`);
  ok('the Sky Fog control drives the fog: tiles form with Fog, fall away when it clears', fg.n2 > fg.n0 + 10 && fg.n3 < fg.n2 && fg.bank === 1, fg);
  const dw = await J(`${PRE} const w = sc.wx; w.fog = 0; sc.tod.e = -3; sc.tod.am = true; sc.wind.v.x = 0.3; sc.wind.v.z = 0.2; F.tick(0.05); F.A.climate(); const k1 = Object.assign({}, F.A.k), w1 = Object.assign({}, F.A.want); sc.tod.e = 50; F.A.climate(); const k2 = Object.assign({}, F.A.k); sc.tod.e = -20; sc.tod.am = false; F.A.climate(); const k3 = Object.assign({}, F.A.k); return JSON.stringify({ dawn: k1.dawn, valley: k1.valley, mist: w1.mist_dawn, noon: k2.dawn, noonValley: k2.valley, nightValley: k3.valley })`);
  ok('dawn mist and valley fog come with the time of day (early morning, and valley fog on still nights), not at noon', dw.dawn > 0.2 && dw.mist > 0.1 && dw.valley > 0 && dw.noon === 0 && dw.noonValley === 0 && dw.nightValley > 0, dw);
  // ---------------------------------------------------------------- quality settings
  const lq = await J(`${PRE} for (const f of F.fires.slice()) F.kill(f, true); F.setPref('low'); F.tick(0.05); const q = F.q; const cp = sc.camera.position; sc.burning.length = 0; sc.HEATP.length = 0; for (const f0 of F.fires.slice()) F.kill(f0, true); const f = F.spawn('campfire', cp.x + 5, Math.max(sc.heightAt(cp.x + 5, cp.z + 5), 0) + 0.05, cp.z + 5, { state: 'burn', dur: 99, pri: 9 }); for (let i = 0; i < 300; i++) { F.tick(0.05); if (F.types.campfire && F.types.campfire.state === 'ready' && F.types.campfire.res === 'low') break; await new Promise(r => setTimeout(r, 100)); } F.tick(0.05); const T = F.types.campfire; return JSON.stringify({ q, res: T && T.res, inst: F.R.inst, vis: f && f.vis })`);
  ok('Fire quality Low reloads the low atlases and still draws', lq.q === 'low' && lq.res === 'low' && lq.inst > 0, lq);
  const off = await J(`${PRE} F.setPref('off'); F.tick(0.05); const r = { q: F.q, fires: F.fires.length, inst: F.R.inst, drawn: F.drawn(window.__t1) }; const t = sc.trees.find(t => !t.dead); sc.igniteTree(t, 20); F.tick(0.05); r.treeDrawn = F.drawn(t); r.legacy = F.legacy(); F.setPref(${PH ? "'low'" : "'high'"}); F.tick(0.05); r.back = F.q; return JSON.stringify(r)`);
  ok('Fire quality Off draws nothing from FW and leaves the old particle fires', off.q === 'off' && off.fires === 0 && off.inst === 0 && !off.treeDrawn && off.legacy, off);
  // ---------------------------------------------------------------- sound (the audio context needs to be running; the headless Chrome here is started with autoplay allowed and muted)
  const au = await J(`const sc = __sc, S = sc.Snd; try { S.init(); } catch (e) {} for (let i = 0; i < 40 && !(S.ready && S.ctx && S.ctx.state === 'running'); i++) { try { if (S.ctx) S.ctx.resume(); } catch (e) {} await new Promise(r => setTimeout(r, 500)); } return JSON.stringify({ ready: S.ready, state: S.ctx && S.ctx.state })`);
  if (au.ready && au.state === 'running') {
    const sn = await J(`${PRE} sc.burning.length = 0; sc.HEATP.length = 0; for (const f of F.fires.slice()) F.kill(f, true); const cp = sc.camera.position; Object.assign(sc.Snd.L, { x: cp.x, y: cp.y, z: cp.z }); const gy = (x, z) => Math.max(sc.heightAt(x, z), 0); for (const [n, dx, dz] of [['campfire', 4, 3], ['vehicle', 14, 9], ['grass', 20, -6]]) F.spawn(n, cp.x + dx, gy(cp.x + dx, cp.z + dz) + 0.05, cp.z + dz, { sc: 1, F: 1, state: 'burn', dur: 999 }); await new Promise(r => setTimeout(r, 300)); for (let k = 0; k < 40; k++) { for (let i = 0; i < 6; i++) F.tick(0.05); await new Promise(r => setTimeout(r, 500)); if (Object.keys(sc.Snd.inst).filter(k => k.startsWith('fw:')).length >= 2) break; } const keys = Object.keys(sc.Snd.inst).filter(k => k.startsWith('fw:')); const lv = keys.map(k => +sc.Snd.inst[k].g.gain.value.toFixed(3)); return JSON.stringify({ keys, lv, loops: F.snd.n.loops, serr: F.snd.err })`);
    ok('fire loops play by size class, near and far twins (camp, vehicle, grass) through Snd.set', sn.keys.length >= 2 && sn.keys.some(k => /camp/.test(k)) && !sn.serr, sn);
    const sh = await J(`${PRE} const cp = sc.camera.position; let src = null; for (let k = 0; k < 40 && !src; k++) { src = F.sndEv('ignite_large', cp.x + 5, cp.z + 5, { y: 1 }); await new Promise(r => setTimeout(r, 500)); } const p0 = sc.Snd.stats.played; for (let i = 0; i < 12; i++) F.sndEv('pop', cp.x + 3, cp.z + 3); const p1 = sc.Snd.stats.played; return JSON.stringify({ played: !!src, burst: p1 - p0, shots: F.snd.played })`);
    ok('one-shots play (ignite_large) and the voice limits hold (12 pops in one frame start at most 3)', sh.played && sh.burst <= 3, sh);
    rep.sound = { loops: sn.keys, oneShot: sh };
  } else { rep.notes.push('audio context not running in this headless Chrome: fire sound NOT exercised (' + JSON.stringify(au) + ')'); log('NOTE audio context not running', JSON.stringify(au)); }
  // ---------------------------------------------------------------- lights pack (needs frames and night)
  await b.ev("window.__qaHold = false; __sc.todSetHour(22.5); 1", true); await sleep(1500);
  const lp = await J(`const sc = __sc, F = sc.FW; for (let i = 0; i < 100 && !F.L.pack && !F.L.failed; i++) await new Promise(r => setTimeout(r, 400)); return JSON.stringify({ pack: !!F.L.pack, failed: F.L.failed, err: F.L.err, fix: sc.LIGHT.fix.length, glb: sc.LIGHT.fix.filter(f => f.glb).length })`);
  ok('lights pack loads', lp.pack, lp);
  rep.lights = lp;
  // the fixtures are laid when the battle starts; if the pack was late they are laid after it loaded
  const lf = await J(`const sc = __sc, F = sc.FW; for (let i = 0; i < 40 && !sc.LIGHT.fix.some(f => f.glb); i++) { try { sc.layPointLights && sc.layPointLights(); } catch (e) {} await new Promise(r => setTimeout(r, 1500)); break; } return JSON.stringify({ glb: sc.LIGHT.fix.filter(f => f.glb).length, kinds: [...new Set(sc.LIGHT.fix.filter(f => f.glb).map(f => f.pkName))], cables: F.L.stats.cables, search: F.L.search.length, models: F.L.stats.models })`);
  ok('modelled fixtures replace the procedural ones (towers, floods, lamps, generators, strings), with cables', lf.glb > 0 && lf.kinds.length >= 3 && lf.cables > 0, lf);
  rep.lights = Object.assign(rep.lights || {}, lf);
  const ln = await J(`const sc = __sc, F = sc.FW; await new Promise(r => setTimeout(r, 12000)); const on = sc.LIGHT.fix.filter(f => f.glb && f.kind !== 'gen' && f.on > 0.5); const f = on[0]; const m0 = f && f.lens[0] && f.lens[0].material && f.lens[0].material.type; if (f) sc.fixDamage(f, 9999, f.x, f.y, f.z); await new Promise(r => setTimeout(r, 2500)); const m1 = f && f.lens[0] && f.lens[0].material && f.lens[0].material.type; const gens = sc.LIGHT.fix.filter(f => f.kind === 'gen'); window.__qaHold = true; let best = null; for (const t of sc.LIGHT.fix) { if (t.kind !== 'tower') continue; let n = 0; for (const o of sc.LIGHT.fix) if (Math.hypot(o.x - t.x, o.z - t.z) < 45) n++; if (!best || n > best.n) best = { n, t }; } let view = null; if (best) { const t = best.t, gy = Math.max(sc.heightAt(t.x, t.z), 0); sc.camera.position.set(t.x + 28, gy + 3, t.z + 28); sc.camera.lookAt(t.x, gy + 4, t.z); sc.camera.updateMatrixWorld(true); const callsOf = () => { sc.renderer.render(sc.scene, sc.camera); return sc.renderer.info.render.calls; }; const all = callsOf(); const fx = sc.LIGHT.fix.filter(f => f.model && f.glb); for (const q of fx) q.model.visible = false; const noFix = callsOf(); for (const q of fx) q.model.visible = true; view = { fixturesNear: best.n, total: all, fixtureModelCalls: all - noFix, models: fx.length }; } return JSON.stringify({ lit: on.length, m0, m1, dead: f && f.dead, gens: gens.length, st: F.L.stats, view })`);
  ok('lamps are lit at night (emissive material) and a shot-out lamp goes dark', ln.lit > 0 && ln.m0 === 'MeshBasicMaterial' && ln.m1 === 'MeshStandardMaterial' && ln.dead, ln);
  if (ln.view) { rep.baseView = ln.view; ok(PH ? 'phone: the lit-base view stays within the 700 draw-call budget and the pack models cost at most 150 of it' : 'the pack models cost at most 150 draw calls in the busiest lit-base view', ln.view.fixtureModelCalls <= 150 && (!PH || ln.view.total <= 700), ln.view); }
  ok('strong-light effects draw at night: flares (and on desktop pools and cones or beam glow)', ln.st.flares > 0 && (PH || ln.st.pools > 0) && (PH || ln.st.cones > 0 || ln.st.glows > 0), ln.st);
  // ---------------------------------------------------------------- performance (staged scene, 30 fires against none), software renderer
  await b.ev("window.__qaHold = true; 1", true);
  const perf = await J(`const sc = __sc, F = sc.FW, gl = sc.renderer.getContext(); const px = new Uint8Array(4); const frame = () => { F.tick(0.016); sc.renderer.render(sc.scene, sc.camera); gl.readPixels(0, 0, 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, px); }; const run = (n) => { const a = []; for (let i = 0; i < n; i++) { const t0 = performance.now(); frame(); a.push(performance.now() - t0); } a.sort((x, y) => x - y); return { mean: +(a.reduce((s, x) => s + x, 0) / n).toFixed(1), p95: +a[Math.floor(n * 0.95)].toFixed(1), min: +a[0].toFixed(1) }; };
    for (const f of F.fires.slice()) F.kill(f, true); F.G.fronts.length = 0; F.G.spots.length = 0; const gy = (x, z) => Math.max(sc.heightAt(x, z), 0); const cp = sc.camera.position; F.setPref(${PH ? "'low'" : "'high'"}); run(3); const base = run(${PH ? 8 : 12}); const cpuRun = (n) => { const a = []; for (let i = 0; i < n; i++) { const t0 = performance.now(); F.tick(0.016); a.push(performance.now() - t0); } a.sort((x, y) => x - y); return { mean: +(a.reduce((s, x) => s + x, 0) / n).toFixed(2), p95: +a[Math.floor(n * 0.95)].toFixed(2) }; }; const cpuBase = cpuRun(60);
    const names = ['campfire', 'barrel', 'vehicle', 'tree_crown', 'grass', 'building']; for (const n of names) F.need(n); for (let i = 0; i < 300; i++) { F.tick(0.02); if (names.every(n => F.types[n] && F.types[n].state === 'ready')) break; await new Promise(r => setTimeout(r, 200)); }
    for (let i = 0; i < 30; i++) { const a = i * 0.9, d = 10 + (i % 6) * 6, x = cp.x + Math.sin(a) * d, z = cp.z + Math.cos(a) * d; F.spawn(names[i % 6], x, gy(x, z) + 0.05, z, { sc: 1, F: 1, state: 'burn', dur: 999, pri: 5, quads: 2 }); }
    sc.camera.lookAt(cp.x + 5, cp.y, cp.z + 25); sc.camera.updateMatrixWorld(true); run(3); const fires = run(${PH ? 8 : 12}); const cpu = { without: cpuBase, with30: cpuRun(60) }; const snapN = F.fires.length, snapInst = F.R.inst, snapCalls = F.R.calls; const callsOf = () => { sc.renderer.render(sc.scene, sc.camera); return sc.renderer.info.render.calls; }; const all = callsOf(); const prevQ = F.pref; F.setPref('off'); F.tick(0.016); const noFW = callsOf(); F.setPref(prevQ); F.tick(0.016); const fx = sc.LIGHT.fix.filter(f => f.model && f.glb); for (const f of fx) f.model.visible = false; const noFix = callsOf(); for (const f of fx) f.model.visible = true; const breakdown = { total: all, withoutFWsprites: noFW, withoutFixtureModels: noFix, fwSprites: all - noFW, fixtureModels: all - noFix, models: fx.length }; return JSON.stringify({ base, fires, n: snapN, inst: snapInst, calls: snapCalls, drawCalls: sc.renderer.info.render.calls, tris: sc.renderer.info.render.triangles, texMB: +(F.R.texBytes() / 1e6).toFixed(1), nTypes: Object.keys(F.types).length + Object.keys(F.A.types).length, cpu, breakdown })`);
  rep.perf = perf; log('perf', JSON.stringify(perf));
  ok('performance measured: 30 fires against none (software renderer; see the report)', perf.fires.mean > 0 && perf.base.mean > 0, perf);
  if (PH) { ok('phone budgets: FW sprites add at most 40 draw calls, atlas memory under 60 MB, fires within the phone cap; the whole scene draw calls are reported against the 700 budget', perf.breakdown.fwSprites <= 40 && perf.texMB < 60 && perf.n <= 14 * 2 + 20, { drawCalls: perf.drawCalls, breakdown: perf.breakdown, texMB: perf.texMB, n: perf.n, over700: perf.drawCalls > 700 }); }
  else ok('decoded atlas memory is about 8 MB per full-size type (checked on this scene)', perf.texMB / Math.max(1, perf.nTypes) < 14, { texMB: perf.texMB, types: perf.nTypes });
  const sw = await J(`const sc = __sc, F = sc.FW; for (const f of F.fires.slice()) F.kill(f, true); F.A.fx.length = 0; F.A.tiles.length = 0; const before = F.R.texBytes() / 1e6, n0 = Object.keys(F.types).length + Object.keys(F.A.types).length; for (const nm in F.types) F.types[nm].last = performance.now() - 400000; for (const nm in F.A.types) F.A.types[nm].last = performance.now() - 400000; F.sweepTypes(); F.A.sweep(); const after = F.R.texBytes() / 1e6, n1 = Object.keys(F.types).length + Object.keys(F.A.types).length; return JSON.stringify({ before: +before.toFixed(1), after: +after.toFixed(1), n0, n1 })`);
  ok('textures are dropped when no fire of that type is left (lazy load, lazy unload)', sw.n1 < sw.n0 && sw.after < sw.before * 0.5, sw);
  // ---------------------------------------------------------------- errors
  ok('no console errors', b.errs.length === 0, b.errs.slice(0, 5));
} catch (e) { ok('check ran to the end without throwing', false, String(e && e.stack || e).slice(0, 400)); }
finally {
  rep.results = results; rep.pass = results.filter(r => r.pass).length; rep.fail = results.filter(r => !r.pass).length; fs.writeFileSync(outFile, JSON.stringify(rep, null, 1));
  log('RESULT', rep.pass, 'passed', rep.fail, 'failed ->', outFile); await g.close(); process.exit(rep.fail ? 1 : 0);
}
